### PR TITLE
reinforce example

### PR DESCRIPTION
**Pull request by justheuristic**
Hello!

Here's a simple REINFORCE tutorial using sonnet.

Is there any chance for it to join the recipes?

### CODE REVIEW

**Comment by justheuristic** [comment]
I signed it!

**Comment by justheuristic** [comment]
Any news on the PR? If it looks to shabby to merge, just say a word and close.

**Comment by malcolmreynolds** [comment]
Hi, thanks for the PR. We can accept this if you upload a new commit which places it inside the (new) directory sonnet/contrib/examples - just so we can make it clear to other users which parts of Sonnet are officially supported etc.

**Comment by justheuristic** [comment]
Hi! Did it.

**Comment by kosklain** [comment]
Merged!

**Pull request closed without merging**
