### PR TITLE
Update io_bazel_rules_closure dependency.

### PR DESCRIPTION
**Pull request by Shuolongbj**
Initial commit.Update io_bazel_rules_closure dependency.

### CODE REVIEW

**Comment by diegolascasas** [comment]
Hi @Shuolongbj, any particular reason for this PR?

The commit in Tensorflow's repository we're pointing to still has the old hash (4be...). When we update the submodule's head (maybe when v1.3 is released) we will also update the hash. Although we might even remove this workaround altogether.

**Comment by Shuolongbj** [comment]
@diegolascasas 
1、Keep updated with TensorFlow.
FYI.
https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE

2、Look forward to your more efficient approach

> Although we might even remove this workaround altogether.

**Comment by diegolascasas** [comment]
Yes, thanks for the clarification.
However, we avoid updating the submodule so it always points to the commit that was tagged with the release version (i.e.[12f033d](https://github.com/tensorflow/tensorflow/tree/12f033df4c8fa3feb88ce936eb1581eaa92b303e)). If you go to that commit you'll see that `io_basel_rules_closure` was not yet updated. 

When Tensorflow 1.3 is released, we will either remove or update the submodule pointer.

**Comment by Shuolongbj** [comment]
got it .thanks!

**Comment by Shuolongbj** [comment]
@diegolascasas 
Submitted the file consistent to the latest r1.3,please refer to.
FYI.
https://github.com/tensorflow/tensorflow/blob/r1.3/WORKSPACE

**Pull request closed without merging**
