### PR TITLE
fix TextModel use_skip_connections usage

### PR DESCRIPTION
**Pull request by albertz**

### CODE REVIEW

**Comment by malcolmreynolds** [comment]
Thanks! Assigning to Diego for merging internally.

Please note: unlike TensorFlow, we will not be directly merging patches via GitHub, as we are our using our internal source control system as the single source of truth for Sonnet. Instead, once reviewed, we will incorporate your change to our system, and then push all changes including yours to GitHub, with a commit which ensures you retain attribution. This process is also used by [Bazel](https://github.com/bazelbuild/bazel). We expect our version of this to be up and running in the next few days - any questions, please let me know.

**Comment by diegolascasas** [comment]
Hi albertz,
Thank you for your contribution, and sorry for the delay.
We are ready to merge your PR, but can you first rebase it to the latest commit?

**Comment by albertz** [comment]
Rebased.

**Comment by diegolascasas** [comment]
Thanks!
We pushed a commit with you as author. 
We had to adapt the way we are exporting the code, so some minor changes in other parts of the code were also included in your commit. They should be only cosmetic, but if you disagree with them being in your commit, please notify us.

**Pull request closed without merging**
