### PR TITLE
Python3 compatibility?

### PR DESCRIPTION
**Pull request by bfredl**
Even if not officiously supported the codebase seems more or less python3 compatible already? Changing one line is enough to import sonnet in python3 and the Shakespeare example works fine after changing `xrange`.

### CODE REVIEW

**Comment by bfredl** [comment]
I signed it!

**Comment by malcolmreynolds** [comment]
Thanks for this - as you say, we knew the codebase was more or less 2/3 compatible but didn't have Python 3 testing infrastructure yet so wanted to err on the side of caution.

Assigning to Diego to test internally & review.

Please note: unlike TensorFlow, we will not be directly merging patches via GitHub, as we are our using our internal source control system as the single source of truth for Sonnet. Instead, once reviewed, we will incorporate your change to our system, and then push all changes including yours to GitHub, with a commit which ensures you retain attribution. This process is also used by [Bazel](https://github.com/bazelbuild/bazel). We expect our version of this to be up and running in the next few days - any questions, please let me know.

**Comment by diegolascasas** [comment]
Hi bfredl,
Thank you for your contribution, and sorry for the delay.
We are ready to merge your PR, but can you first rebase it to the latest commit and solve the conflicts?
Note that we added some bits of functionality to the code. They were already in the process of being released and we needed to add them before accepting any PR. Can you verify your changes still make sonnet Python3 compatible?

**Comment by bfredl** [comment]
> Can you verify your changes still make sonnet Python3 compatible?

Mostly, the new `testing/parameterized/parameterized.py` caused some trouble. 

The only remaining sonnet failure is:
```
======================================================================
ERROR: testHasVariableScope (sonnet.python.modules.util_test.UtilTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bjorn/dev/sonnet/sonnet/python/modules/util_test.py", line 258, in testHasVariableScope
    self.assertTrue(snt.has_variable_scope(linear))
  File "/home/bjorn/dev/sonnet/sonnet/python/modules/util.py", line 312, in has_variable_scope
    return hasattr(obj, "variable_scope") or "variable_scope" in dir(obj)
  File "/home/bjorn/dev/sonnet/sonnet/python/modules/base.py", line 261, in variable_scope
    self._ensure_is_connected()
  File "/home/bjorn/dev/sonnet/sonnet/python/modules/base.py", line 351, in _ensure_is_connected
    "first.".format(self.scope_name))
sonnet.python.modules.base.NotConnectedError: Variables in linear not instantiated yet, __call__ the module first.
```

But there some more failures in the parameterized tests tests:
https://gist.github.com/bfredl/60f529c629e48e72d5e19824be271a83

I might look into them later.

**Comment by bfredl** [comment]
Now I get exactly the same errors in python2 and python3, so they're probably due to differences in testing environment. Apart from building I just set `TEST_SRCDIR` and run `nosetests2/3`. I use recent-ish tensorflow-git.

@diegolascasas would you be able to run the tests with python3 on your infrastructure?

**Comment by malcolmreynolds** [comment]
@bfredl we hope to have python3 internal testing up and running shortly.

**Comment by Tutufa** [comment]
would really appreciate python3 support)

**Comment by diegolascasas** [comment]
@bfredl, this pull request is now merged with you as author.
Thank you for your contribution!

**Comment by bfredl** [comment]
Maybe add a note to README that python 3 is now supported?

**Comment by guillaume-chevalier** [comment]
How should one build Sonnet for Python 3? 

I tried to set the TensorFlow headers for Python 3, and it compiles... however the result of the compilation is a `.whl` wheel file that is only compatible with Python 2. 

Surprisingly, the wheel works correctly in Python 2 after a pip install, despite the tf headers config. But, how to compile explicitly for Python 3 and pip3? With pip3, it says that it is "not a supported wheel on this platform."

**Comment by Krailon** [comment]
@guillaume-chevalier it turned out to be easier than I thought it would be:
`sed -i 's/python /python3 /' bazel-bin/install`
`./bazel-bin/install /tmp/sonnet`
`pip3 install /tmp/sonnet/*.whl`

Tested and working in Python 3.5.2.

**Pull request closed without merging**
