### PR TITLE
Hardcoded path in rnn_shakespear_test.py

### PR DESCRIPTION
**Pull request by esc**
The path is here:

https://github.com/deepmind/sonnet/blob/master/sonnet/examples/dataset_shakespeare.py#L88

```
esc@omnitech ~/git/sonnet/sonnet/examples (git)-[master] % python rnn_shakespeare_test.py 
E.
======================================================================
ERROR: testRun (__main__.TinyShakespeareTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "rnn_shakespeare_test.py", line 31, in testRun
    rnn_shakespeare.train(10, 10, 9)
  File "/home/esc/git/sonnet/.venv/local/lib/python2.7/site-packages/sonnet/examples/rnn_shakespeare.py", line 180, in train
    name="shake_train")
  File "/home/esc/git/sonnet/.venv/local/lib/python2.7/site-packages/sonnet/examples/dataset_shakespeare.py", line 127, in __init__
    vocab_data_file=self._vocab_file)
  File "/home/esc/git/sonnet/.venv/local/lib/python2.7/site-packages/sonnet/examples/dataset_shakespeare.py", line 58, in __init__
    token_list = reading_function(vocab_data_file)
  File "/home/esc/git/sonnet/.venv/local/lib/python2.7/site-packages/sonnet/examples/dataset_shakespeare.py", line 53, in reading_function
    return list(f.read().replace("\n", self.CHAR_EOS))
  File "/home/esc/git/sonnet/.venv/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 115, in read
    self._preread_check()
  File "/home/esc/git/sonnet/.venv/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 75, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/esc/git/sonnet/.venv/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
NotFoundError: /cns/wj-d/home/deepmind/sequence_data/ts/ts.train.txt

----------------------------------------------------------------------
Ran 2 tests in 0.004s

FAILED (errors=1)
```

### CODE REVIEW

**Comment by esc** [comment]
Yes, I have just signed the thing!

**Comment by kosklain** [comment]
We really appreciate that you noticed this, as Tim said this got in when merging new changes. In order to have a clean commit history with the correct path at all times, I fixed the mistake in the corresponding spurious commit (this will unfortunately break your local repository, you may need to re-clone). I'll close this for now, my apologies since in this case the credit assignment is not ideal!

**Comment by esc** [comment]
Just to clarify: you will force update the 'deepmind/sonnet'  'master' on github?

On 15 April 2017 00:17:10 CEST, "Adrià Puigdomènech" <notifications@github.com> wrote:
>We really appreciate that you noticed this, as Tim said this got in
>when merging new changes. In order to have a clean commit history with
>the correct path at all times, I fixed the mistake in the corresponding
>spurious commit (this will unfortunately break your local repository,
>you may need to re-clone). I'll close this for now, my apologies since
>in this case the credit assignment is not ideal!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deepmind/sonnet/pull/19#issuecomment-294247069

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kosklain** [comment]
Yes, that has been done now. We've put more checks in our exportation procedure to avoid this situation in the future.

**Comment by esc** [comment]
I am not sure how familiar you are with git, but you do realize that force-pushing a `master` branch does present somewhat of a risk?

I see that, with such a small history and limited number of public clones this may be considered a reasonable thing to do. However, at least one person has already executed a `git pull` on their local clone: https://github.com/deepmind/sonnet/network which means that old and new history have been merged there. (Which is exactly the danger of force-pushing to `master`).

Is something like this likely to happen again? If yes, do you intend to create some guidelines as to how people should be using their forks and clones?

**Comment by esc** [comment]
Incidentally, you may want to notify @rakshit-agrawal that his fork is broken and needs to be fixed.

**Comment by kosklain** [comment]
Thanks for raising this.

As you mention, doing this has a high risk, and we are fully aware of that. It is also by the reasons you point out that we still did it in this case (low number of public clones + being only in its first 1.5 weeks). If this same situation were to happens at any point in the future, history rewrite will surely be our last resort (as it should be for any git repository, again for those reasons). All PRs will be notified of the required rebase.

**Comment by esc** [comment]
Thanks so much for your swift response--- and all good then! You have convinced me you know what you are doing.

**Comment by rakshit-agrawal** [comment]
Thanks @esc 
Updated the fork to match with new master branch.

**Comment by esc** [comment]
Looks good!

**Pull request closed without merging**
